[package]
authors = ["insanitybit <insanitybit@gmail.com>"]
name = "playrust_alert"
version = "0.1.0"

[dependencies]
clap = "2.9.2"
csv = "0.14.*"
hyper = "0.9.*"
ndarray = "0.6"
rand = "0.3.*"
rayon = "0.4.0"
rustc-serialize = "*"
serde = "0.7.*"
serde_json = "0.7.*"
serde_macros = "0.7.*"
stopwatch = "*"
rust-tfidf = "1.0.*"
tiny-keccak = "1.0.*"

[dependencies.rsml]
path = "../rsml/"

# The release profile, used for `cargo build --release`.
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
# panic = 'abort'

# -C target-feature and -C target-cpu
